services:
  - type: web
    name: pocket-signal-bot
    runtime: python

    buildCommand: pip install -r requirements.txt

    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: PYTHON_VERSION
        value: 3.13.5

      - key: BOT_TOKEN
        sync: false

      - key: ADMIN_ID
        sync: false

      - key: TWELVE_DATA_API_KEY
        sync: false

      - key: MIN_QUALITY
        value: "85"

      - key: AUTO_SCAN_SECONDS
        value: "60"

      - key: CANDLE_INTERVAL
        value: "5min"

      - key: CANDLE_LIMIT
        value: "200"
